[tool.poetry]
name = "loafer-handler"
version = "0.1.0"
description = ""
authors = ["rafael.emery <rafael.emery@olist.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
loafer = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
